---
- hosts: aws  #Inventory group name from ansible/hosts file
  user: ec2-user
  sudo: true

  vars:
    pack_name: httpd
    serv_name: httpd

  tasks:
    - name: Install {{ pack_name }}  #Replace vaiables from vars: section
      yum: pkg={{ pack_name }} state=installed
    - name: Start service {{ serv_name }}
      service: name={{ serv_name }} state=started
...
